### ISSUE TITLE
sectigo-client not on the newest version

### ISSUE THREAD

**Issue by albanbruder** [hm-edu/pki-portal-backend#264]
Hi @fritterhoff,

thanks for the quick patch in https://github.com/hm-edu/sectigo-client/commit/3ce2968da49d3a9821519071ed5a7dfd97def1b1!

It seems that this repository doesn't contain the patch yet. The go.mod file of the pki service still points to an old commit: https://github.com/hm-edu/portal-backend/blob/main/backend/pki-service/go.mod#L6

However, if you update the go.mod file locally and rebuild the container, the patch will work as intended.

**Comment by fritterhoff** [comment]
Sadly I forgot to merge the MR ...
