### ISSUE TITLE
Änderungen in GÉANT TCS wg. SMIME-BRs

### ISSUE THREAD

**Issue by albanbruder** [hm-edu/pki-portal-backend#267]
Hallo @fritterhoff,

ihr habt die kurzfristige Meldung vom DFN sicherlich auch bekommen. Falls nicht würde ich die mMn relevanten Informationen hier nochmal kurz festhalten.

Sectigo hat u.a. die folgenden Hinweise veröffentlicht: 
https://www.sectigo.com/knowledge-base/detail/New-CA-Browser-Forum-Compliant-Public-S-MIME-Certificates-in-SCM/kA05c000000ku9d

Ab 28.08., 9:00 UTC, sind nur Client-Zertifikate nach den neuen Profilen beziehbar.

Abwandlung des Verfahrens bei API-Zugriff notwendig: Nicht mehr nur `api/smime/v1/enroll`, 
sondern eine Abfolge von `api/person/v1` (mit Parameter 'validationType': 
'HIGH') und `api/smime/v1/enroll`. Bei /enroll muss eine neue Profilnummer 
gewählt werden. Welche dies ist, steht ab 21.08. fest.

Sag bitte Bescheid, falls wir dich bei der Umsetzung durch ein MR unterstützen können.

**Comment by fritterhoff** [comment]
Hi,

ja, wir haben wir Mitteilung auch bekommen. Ich habe es mal überflogen. Prinzipiell schaut das Ganze nach nicht zu viel Arbeit aus. Ich würde das nach den Anpassungen seitens Sectigo nächste Woche implementieren.

**Comment by fritterhoff** [comment]
@albanbruder wir würden vrstl. pauschal Nutzer mit `validationType: High` anlegen und entsprechnde Zertifikate ausstellen. Würdest du eine Unterscheidung an bestimmten Attributen vornehmen? z.B. Studis v.s. Mitarbeiter oder so?

**Comment by albanbruder** [comment]
Danke fürs Nachfragen. Wir würden da bei uns auch nicht zwischen Studierenden und Mitarbeitern unterscheiden.

**Comment by fritterhoff** [comment]
Nach interner Diskussion werden wir bei uns (vorerst) die Ausstellung von SMIME Zertifikaten für Studierende per optionalem Flag deaktivieren.
