### ISSUE TITLE
feat: Support S/MIME group certificates

### ISSUE THREAD

**Issue by albanbruder** [hm-edu/pki-portal-backend#300]
1. I suggest that we extend the `/smime/csr` handlers `CsrRequest` as follows

```go
// CsrRequest holds a CSR.
type CsrRequest struct {
	CSR string `json:"csr" validate:"required"`.
       Email string `json:"email" validate:"email"`
}
```
We obviously need to duplicate this struct to support both ssl and smime requests. The frontend can extract the group emails the user has access to from either the access_token or the id_token.

2. I am not sure which is the best claim for this purpose. However, I suggest that we do not reuse/abuse a standardised claim, but rather define our own. For example: `{"additionalSmimeEmails": ["group-aa@example.org", "group-b@example.org"]}` 
@fritterhoff What do you think?

3. The pki-rest-interface checks if a user is authorised for a given email by checking both the email and the additionalSmimeEmails claims. If the requested email matches the user's primary email, we enroll the certificate with validationType HIGH and the profile information extracted from the access_token. If the requested email is included in the additionalSmimeEmails claim, we enroll the certificate with validationType STANDARD.

4. An open question is what to use as the firstName of " person " (as it seems to be required by the Sectigo API). DFN suggests `GRP - IT Helpdesk`. However, we do not have this kind of information with the custom claim described above. Another possibility is to use `GRP - group@example.org`. Whatever we use: If I understand the documentation correctly, when using validationType STANDARD, only the email will be included in the certificate. 
@fritterhoff Which one do you prefer?

5. We need to extend the SmimeService's gRPC API to allow the pki-rest-interface to specify the validationType.

**Comment by fritterhoff** [comment]
> 1. I suggest that we extend the `/smime/csr` handlers `CsrRequest` as follows
> 
> 
> ```go
> // CsrRequest holds a CSR.
> type CsrRequest struct {
> 	CSR string `json:"csr" validate:"required"`.
>        Email string `json:"email" validate:"email"`
> }
> ```
> 
> We obviously need to duplicate this struct to support both ssl and smime requests. The frontend can extract the group emails the user has access to from either the access_token or the id_token.

I think that's that solution makes sense :) From my point of view the other solution would be to encode the requested email(s) inside the CSR and decode it server-side and check the request. Regardless which solution we chose I would consider to allow multiple E-Mail(s)? 
 
> 2. I am not sure which is the best claim for this purpose. However, I suggest that we do not reuse/abuse a standardised claim, but rather define our own. For example: `{"additionalSmimeEmails": ["group-aa@example.org", "group-b@example.org"]}`
> @fritterhoff What do you think?
> 

Yes. I would introduce a new claim. However, based on the existing properties, I would prefer a name with an underscore.


> 3. The pki-rest-interface checks if a user is authorised for a given email by checking both the email and the additionalSmimeEmails claims. If the requested email matches the user's primary email, we enroll the certificate with validationType HIGH and the profile information extracted from the access_token. If the requested email is included in the additionalSmimeEmails claim, we enroll the certificate with validationType STANDARD.

✅ 

> 4. An open question is what to use as the firstName of " person " (as it seems to be required by the Sectigo API). DFN suggests `GRP - IT Helpdesk`. However, we do not have this kind of information with the custom claim described above. Another possibility is to use `GRP - group@example.org`. Whatever we use: If I understand the documentation correctly, when using validationType STANDARD, only the email will be included in the certificate.
>        @fritterhoff Which one do you prefer?

From my point of view this information is not included in any property and only stored in the backend of sectigo itself. For this reason I would prefer a solution that is as simple as possible. I could imagine that alternative data sources (LDAP, other databases,...) could be used here, but this would probably be complex.

>  5. We need to extend the SmimeService's gRPC API to allow the pki-rest-interface to specify the validationType.

Yes :)

One further change has to be done beside the issuance: We must query the certificates for all emails included in the SAN or must add a filter param to the GET endpoint.

**Comment by albanbruder** [comment]
>I think that's that solution makes sense :) From my point of view the other solution would be to encode the requested email(s) inside the CSR and decode it server-side and check the request. Regardless which solution we chose I would consider to allow multiple E-Mail(s)?

I prefer the solution where the email is encoded in the CSR because then we would have a similar interface to the SSL API.

What is your use case for having multiple emails in a certificate? Talking to my colleagues, we prefer certificates with only one email because: What validation type should the person/certificate have if both primary and group emails are required? What happens if a person leaves a group but continues to use the certificate? If you need this functionality, maybe we can enable/disable it with a feature flag?

> From my point of view this information is not included in any property and only stored in the backend of sectigo itself. For this reason I would prefer a solution that is as simple as possible. I could imagine that alternative data sources (LDAP, other databases,...) could be used here, but this would probably be complex.

If it is not included in the certificate I would prefer a simple solution.

> One further change has to be done beside the issuance: We must query the certificates for all emails included in the SAN or must add a filter param to the GET endpoint.

Both could be useful. However, I do not believe that the Sectigo API has support for listing S/MIME certificates for multiple emails. We either need to fetch/cache all certificates (similar to SSL certificates) or call the Sectigo API multiple times. I strongly prefer the second one however this depends on the number of emails a user is authorized to access.

**Comment by fritterhoff** [comment]
Well okay. The idea regarding multiple E-Mails was only a quick note :-) Probably your right. The use cases are pretty limited. 

I will check what attributes are included in which field. According to the docs and the mailing-lists the CN, First- & Lastname are not included in the certificate but I never tried.

From my point of view the filter option would be the simplest. For this use case we only must extend the existing endpoint and crawl the sectigo endpoint instead of joining several results.

**Comment by fritterhoff** [comment]
Hi @albanbruder I just started to extend some servies a little bit. In detail: 

- The GRPC api now has an optional argument to lower the validation level
- The PKI Backend Service is able to issue an "Standard" SMIME Cert.

The next steps would be to extend the Rest-API

**Comment by albanbruder** [comment]
@fritterhoff Thank you for extending the GRPC API.

I've extended the pki-rest-interface as described in https://github.com/hm-edu/portal-backend/pull/310. You would still need to update the portal frontend. But the API should be backwards compatible.

**Comment by albanbruder** [comment]
Implemented by https://github.com/hm-edu/portal-backend/pull/310
